In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 0.5])
w1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
b1 = np.array([0.1, 0.2, 0.3])

In [3]:
a1 = np.dot(x, w1)
a1

array([0.2, 0.5, 0.8])

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
z1 = sigmoid(a1)
z1

array([0.549834  , 0.62245933, 0.68997448])

In [6]:
w2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])

In [7]:
b2 = np.array([0.1, 0.2])

In [8]:
a2 = np.dot(z1, w2) + b2
z2 = sigmoid(a2)

In [9]:
def identity_function(x):
    return x

In [10]:
w3 = np.array([[0.1, 0.3], [0.2, 0.4]])
b3 = np.array([0.1, 0.2])

In [11]:
a3 = np.dot(z2, w3) + b3
y = identity_function(a3)

In [12]:
y

array([0.3136521, 0.6892316])