# Artificial Neural Network

### Importing the libraries

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [37]:
tf.__version__

'2.17.0'

### Importing the dataset

In [38]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [39]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding categorical data

Label Encoding the "Gender" column

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [41]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [43]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [46]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [47]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [48]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [49]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [50]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [51]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Epoch 1/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 287us/step - accuracy: 0.7987 - loss: 0.5490
Epoch 2/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 235us/step - accuracy: 0.7929 - loss: 0.4631
Epoch 3/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 237us/step - accuracy: 0.8082 - loss: 0.4339
Epoch 4/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 236us/step - accuracy: 0.8099 - loss: 0.4276
Epoch 5/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - accuracy: 0.8123 - loss: 0.4282
Epoch 6/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 235us/step - accuracy: 0.8211 - loss: 0.4152
Epoch 7/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 235us/step - accuracy: 0.8175 - loss: 0.4173
Epoch 8/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 236us/step - accuracy: 0.8180 - loss: 0.4251
Epoch 9/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - accuracy: 0.8156 - loss: 0.4153
Epoch 10/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - accuracy: 0.8199 - loss: 0.4105
Epoch 11/1000
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - accuracy: 0.8182 - loss: 0.4183
Epoch 12

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [62]:
print(ann.predict(sc.transform([[1, 0, 0, 500, 1, 10, 3, 10000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [65]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

test_bad_count = 0
test_good_count = 0

for result in np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1):
    if result[0] != result[1]:
        test_bad_count += 1

print(test_bad_count)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step
273


### Making the Confusion Matrix

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 195  210]]


0.8635