In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [13]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.14667332,  0.3020472 ,  0.22567256,  0.23997143,  0.47358346,
         0.5525814 , -0.655051  ,  0.49125314,  0.3562298 , -1.4031763 ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.07249887, 0.11355547, 0.10520563, 0.10672076, 0.1348048 ,
        0.14588603, 0.04360593, 0.13720793, 0.11987794, 0.02063664]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - accuracy: 0.9896 - loss: 0.0311
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.9905 - loss: 0.0266
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.9904 - loss: 0.0280
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.9910 - loss: 0.0275
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.9922 - loss: 0.0234
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.9919 - loss: 0.0235
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 722us/step - accuracy: 0.9915 - loss: 0.0234
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.9923 - loss: 0.0225
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.9915 - loss: 0.0234
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 735us/step - accuracy: 0.9929 - loss: 0.0190


In [25]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - 268us/step - accuracy: 0.9802 - loss: 0.0934


[0.09339553862810135, 0.9801999926567078]

In [30]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [31]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.86969199e-13, 8.86452405e-17, 7.20113726e-12, 5.29642705e-07,
        1.27802085e-17, 2.10999075e-14, 2.67110010e-19, 9.99998093e-01,
        1.91310379e-12, 1.44956061e-06],
       [2.21026230e-20, 2.40763989e-11, 1.00000000e+00, 1.08306137e-12,
        1.57607484e-29, 4.13170149e-12, 1.20613296e-16, 6.35980962e-30,
        5.76747804e-16, 6.74133210e-28],
       [1.36654065e-11, 9.99986410e-01, 1.52257951e-06, 3.71635944e-10,
        3.22339311e-08, 1.54998861e-11, 1.79723147e-09, 9.91540765e-06,
        2.20530842e-06, 8.50924759e-14],
       [1.00000000e+00, 1.88329918e-17, 1.06817142e-08, 9.22576970e-14,
        3.68091593e-15, 1.71646690e-11, 1.13014190e-11, 4.64094985e-09,
        4.51398003e-15, 2.44061216e-10],
       [2.25335393e-11, 2.14100812e-17, 2.00149164e-12, 8.27151221e-15,
        9.99387622e-01, 8.89320935e-17, 7.81834320e-11, 6.04509864e-07,
        2.05025246e-13, 6.11720490e-04]], dtype=float32)>

In [33]:
import numpy as np

def get_result_model(probability_array):
    return np.max(probability_array.numpy(), axis=1, keepdims=True)

In [36]:
get_result_model(probability_model(x_test[:5]))

array([[0.9999981],
       [1.       ],
       [0.9999864],
       [1.       ],
       [0.9993876]], dtype=float32)