In [3]:
import tensorflow as tf

x = tf.constant([[1, 2, 3], [4, 5, 6]])

x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

# tf variable

In [7]:
var = tf.Variable([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

var

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>